name: __PROJECT_NAME__
options:
  deploymentTarget:
    iOS: 14.0
  xcodeVersion: "12.5"
  bundleIdPrefix: com.exam
settings:
  MARKETING_VERSION: 0.0.1
configs:
  Debug: debug
  Staging: release
  Release: release
targets:
  __PROJECT_NAME__:
    type: application
    platform: iOS
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
      configs:
        Staging:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "STAGING"
    sources:
      - __PROJECT_NAME__
    scheme:
      testTargets:
        - __PROJECT_NAME__Tests
  __PROJECT_NAME__Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - __PROJECT_NAME__Tests
    dependencies:
      - target: __PROJECT_NAME__
