name: __PROJECT_NAME__
options:
  deploymentTarget:
    iOS: 14.0
  xcodeVersion: "12.5"
  bundleIdPrefix: com.exam
settings:
  MARKETING_VERSION: 0.0.1
configs:
  Debug: debug
  Staging: release
  Release: release
targetTemplates:
  framework-base:
    type: framework
    platform: iOS
    sources:
      - path: ${target_name}
  unittest-base:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ${target_name}
    
targets:
  __PROJECT_NAME__:
    type: application
    platform: iOS
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
      configs:
        Staging:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "STAGING"
    sources:
      - App
    scheme:
      testTargets:
        - AppTests
  __PROJECT_NAME__Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - AppTests
    dependencies:
      - target: __PROJECT_NAME__
